#!/usr/bin/python2
#
# Copyright (C) 2007-2019  CZ.NIC, z. s. p. o.
#
# This file is part of FRED.
#
# FRED is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRED is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRED.  If not, see <https://www.gnu.org/licenses/>.

"""
This is a simple nagios compatible script, which tests functionality of
CORBA genzone server. Nagios compatible means, that its return code and
output is in accordance to nagios expectations.

Tester sends a request for zone transfer and then closes the transfer without
transfering any data (only SOA record is transferred as result of openning
transaction). Therefore this test is not resource demanding.
"""
from pyfred.commands.check_pyfred_genzone import run_check_pyfred_genzone

if __name__ == "__main__":
    run_check_pyfred_genzone()
